import fs from "node:fs";
import net from "node:net";
import path from "node:path";

/**
 * Zero-config "Run" resolver.
 *
 * Most NeonDeck starter projects (every template + the blank scaffold) are plain
 * static HTML/CSS/JS sites with no `package.json` and no dev server. The old
 * default Run command (`npm install && npm run dev`) therefore never bound a port
 * and the preview iframe immediately hit `ECONNREFUSED 127.0.0.1:3000`.
 *
 * `resolveStartCommand` inspects the workspace and picks the right command:
 *   • a package.json with a `dev`/`start` script  → npm install && npm run <it>
 *   • anything else (a static site)               → a tiny built-in static server
 *
 * The static server is dependency-free (Node core only) and is written into the
 * workspace under `.neondeck/` (hidden from the file tree), so it works the same
 * in LOCAL_NODE and inside a mounted Docker container.
 */

/** The Run command the LiveView sends by default; we auto-detect when we see it. */
export const DEFAULT_RUN_COMMAND = "npm install && npm run dev";

const SERVE_DIR = ".neondeck";
const SERVE_FILE = "serve.cjs";

/** Source of the built-in static file server (serves its grandparent = wsDir). */
const STATIC_SERVER_SRC = `// Auto-generated by NeonDeck — a tiny static preview server (Node core only).
const http = require("http");
const fs = require("fs");
const path = require("path");
const port = Number(process.argv[2]) || 3000;
const root = path.resolve(__dirname, "..");
const TYPES = {
  ".html": "text/html; charset=utf-8", ".htm": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8", ".mjs": "text/javascript", ".cjs": "text/javascript",
  ".jsx": "text/javascript", ".ts": "text/javascript", ".tsx": "text/javascript",
  ".css": "text/css; charset=utf-8", ".json": "application/json",
  ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".gif": "image/gif",
  ".svg": "image/svg+xml", ".ico": "image/x-icon", ".webp": "image/webp", ".avif": "image/avif",
  ".woff": "font/woff", ".woff2": "font/woff2", ".ttf": "font/ttf", ".otf": "font/otf",
  ".map": "application/json", ".wasm": "application/wasm",
  ".mp3": "audio/mpeg", ".wav": "audio/wav", ".mp4": "video/mp4",
  ".txt": "text/plain; charset=utf-8"
};
function serveFile(res, file) {
  const type = TYPES[path.extname(file).toLowerCase()] || "application/octet-stream";
  res.writeHead(200, { "content-type": type, "cache-control": "no-store" });
  fs.createReadStream(file).pipe(res);
}
http.createServer(function (req, res) {
  try {
    let urlPath = decodeURIComponent((req.url || "/").split("?")[0]);
    if (urlPath.endsWith("/")) urlPath += "index.html";
    let file = path.join(root, urlPath);
    if (file !== root && file.indexOf(root + path.sep) !== 0) { res.writeHead(403); return res.end("Forbidden"); }
    if (fs.existsSync(file) && fs.statSync(file).isFile()) return serveFile(res, file);
    const idx = path.join(root, "index.html"); // SPA / pretty-url fallback
    if (fs.existsSync(idx)) return serveFile(res, idx);
    res.writeHead(404, { "content-type": "text/plain" });
    res.end("404 Not Found: " + urlPath);
  } catch (e) {
    res.writeHead(500, { "content-type": "text/plain" });
    res.end("500 " + (e && e.message));
  }
}).listen(port, "0.0.0.0", function () {
  console.log("NeonDeck static server ready on http://127.0.0.1:" + port);
});
`;

/** Write the static server into <wsDir>/.neondeck/serve.cjs and return its rel path. */
function writeStaticServer(workspaceDir: string): string {
  const dir = path.join(workspaceDir, SERVE_DIR);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, SERVE_FILE), STATIC_SERVER_SRC, "utf8");
  return `${SERVE_DIR}/${SERVE_FILE}`;
}

export interface ResolvedStart {
  command: string;
  kind: "node" | "static";
}

/** Decide how to start the workspace given its contents. */
export function resolveStartCommand(workspaceDir: string, appPort: number): ResolvedStart {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(workspaceDir, "package.json"), "utf8"));
    const scripts = (pkg.scripts ?? {}) as Record<string, string>;
    if (typeof scripts.dev === "string") return { command: "npm install && npm run dev", kind: "node" };
    if (typeof scripts.start === "string") return { command: "npm install && npm start", kind: "node" };
  } catch {
    /* no/invalid package.json → treat as a static site */
  }
  const rel = writeStaticServer(workspaceDir);
  return { command: `node ${rel} ${appPort}`, kind: "static" };
}

/**
 * Resolve once a TCP server accepts a connection on 127.0.0.1:port, polling
 * every 300ms until `timeoutMs` elapses. Used to nudge the preview iframe to
 * reload only after the app is actually listening (so the first paint isn't a
 * 502 from the proxy racing the dev server's startup).
 */
export function waitForPort(port: number, timeoutMs = 120_000): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  return new Promise((resolve) => {
    const tryOnce = () => {
      const sock = net.connect({ host: "127.0.0.1", port });
      sock.setTimeout(2_000);
      const retry = () => {
        sock.destroy();
        if (Date.now() > deadline) return resolve(false);
        setTimeout(tryOnce, 300);
      };
      sock.once("connect", () => {
        sock.destroy();
        resolve(true);
      });
      sock.once("error", retry);
      sock.once("timeout", retry);
    };
    tryOnce();
  });
}
